Repository v3io/v3io-tsdb, pull requests merged in 2018-11, with the labels that each got.

#208 Update travis configuration for bench test
  travis_v3io_bench.yaml
Labels: CI

#190 TSDB-52: Fix partial partition delete
  pkg/partmgr/partmgr.go
  pkg/partmgr/partmgr_test.go
  pkg/querier/querier.go
  pkg/tsdb/v3iotsdb.go
  pkg/tsdb/v3iotsdb_integration_test.go
  pkg/tsdbctl/delete.go
Labels: Documentation, bug, no-test

#219 Add build info and version info to TSDB at build time
  Makefile
  pkg/config/config.go
  pkg/tsdb/tsdbtest/config_test.go
  pkg/tsdbctl/tsdbctl.go
  pkg/tsdbctl/version.go
Labels: Documentation, enhancement

#218 Use `tsdbtest.TestParams` to control the input params and flow of an integration test
  examples/nuclio/ingest/ingest_example_integration_test.go
  examples/nuclio/query/query_example_integration_test.go
  pkg/tsdb/tsdb_integration_test.go
  pkg/tsdb/tsdbtest/tsdbtest.go
  pkg/tsdb/v3iotsdb_integration_test.go
Labels: enhancement
